import type { Card } from "@/lib/types";

// Home-fan showcase: baked example cards so the homepage's card fan renders
// without a backend round trip. These are real, live-fetched snapshots of
// actual top-ranked LeetCode profiles (via the backend's /card/:username at
// the time this file was written) — not illustrative placeholders. Every card
// still resolves to a live (re-fetched, possibly-changed) scout when clicked.

export const SAMPLE_CARDS: Card[] = [
  {
    username: "skywalkert",
    name: "Jingzhe Tang",
    avatarUrl: "https://assets.leetcode.com/users/t251346744/avatar_1587471563.png",
    country: "cn",
    stats: { pac: 65, sho: 86, pas: 94, dri: 80, def: 74, phy: 78 },
    position: "CM",
    family: "Playmaker",
    baseOvr: 83,
    overall: 91,
    finish: "icon",
    archetype: "Grandmaster",
    archetypeBlurb: "hall-of-fame solver — high and balanced, earned over years",
    legacy: 0.7130167562144185,
    skillMoves: 5,
    weakFoot: 5,
    workRateAttack: "High",
    workRateDefense: "High",
    style: "Industrious",
    playstyles: [
      { name: "Hard Hitter", plus: true, reason: "870 Hard problems solved — elite tier." },
      { name: "Contest Grinder", plus: true, reason: "217 contests attended — elite tier." },
      { name: "Completionist", plus: true, reason: "3687 total problems solved — elite tier." },
      { name: "Polymath", plus: true, reason: "46 topics solved — elite tier." },
      { name: "Speed Solver", plus: true, reason: "634 problems solved this year — elite tier." },
      { name: "Specialist", plus: true, reason: "18 hard-tier topics solved — elite tier." },
      { name: "Polyglot", plus: true, reason: "6 languages used — elite tier." },
      { name: "Ranked", plus: true, reason: "2708 contest rating — elite tier." },
    ],
    contestRating: 2708.13,
    contestsAttended: 217,
    totalSolved: 3687,
    easySolved: 903,
    mediumSolved: 1914,
    hardSolved: 870,
    topicsSolved: 46,
    easyTopicsSolved: 10,
    mediumTopicsSolved: 18,
    hardTopicsSolved: 18,
    languagesUsed: 6,
    reputation: 9,
    activeDays: 301,
  },
  {
    username: "cpcs",
    name: "Peng Cao",
    avatarUrl: "https://assets.leetcode.com/users/avatars/avatar_1673539266.png",
    country: "us",
    stats: { pac: 67, sho: 85, pas: 94, dri: 81, def: 67, phy: 78 },
    position: "CM",
    family: "Playmaker",
    baseOvr: 82,
    overall: 90,
    finish: "icon",
    archetype: "Grandmaster",
    archetypeBlurb: "hall-of-fame solver — high and balanced, earned over years",
    legacy: 0.7234138375430651,
    skillMoves: 5,
    weakFoot: 4,
    workRateAttack: "High",
    workRateDefense: "Med",
    style: "Relentless",
    playstyles: [
      { name: "Hard Hitter", plus: true, reason: "951 Hard problems solved — elite tier." },
      { name: "Speed Solver", plus: true, reason: "2854 problems solved this year — elite tier." },
      { name: "Completionist", plus: true, reason: "3985 total problems solved — elite tier." },
      { name: "Streak Keeper", plus: true, reason: "283 day streak — elite tier." },
      { name: "Polymath", plus: true, reason: "46 topics solved — elite tier." },
      { name: "Polyglot", plus: true, reason: "18 languages used — elite tier." },
      { name: "Specialist", plus: true, reason: "18 hard-tier topics solved — elite tier." },
      { name: "Sharpshooter", plus: true, reason: "100 % acceptance rate — elite tier." },
    ],
    contestRating: 2449.563,
    contestsAttended: 22,
    totalSolved: 3985,
    easySolved: 953,
    mediumSolved: 2081,
    hardSolved: 951,
    topicsSolved: 46,
    easyTopicsSolved: 10,
    mediumTopicsSolved: 18,
    hardTopicsSolved: 18,
    languagesUsed: 18,
    reputation: 4767,
    activeDays: 363,
  },
  {
    username: "SupremeChicken",
    name: "SupremeChicken",
    avatarUrl: "https://assets.leetcode.com/users/SupremeChicken/avatar_1757950913.png",
    country: "us",
    stats: { pac: 83, sho: 87, pas: 95, dri: 75, def: 58, phy: 75 },
    position: "ST",
    family: "Forward",
    baseOvr: 81,
    overall: 89,
    finish: "chrome",
    archetype: "Sprinter",
    archetypeBlurb: "the engine — a daily-driver who never slows down",
    legacy: 0.6949794135857856,
    skillMoves: 5,
    weakFoot: 4,
    workRateAttack: "High",
    workRateDefense: "Med",
    style: "Explosive",
    playstyles: [
      { name: "Speed Solver", plus: true, reason: "24182 problems solved this year — elite tier." },
      { name: "Hard Hitter", plus: true, reason: "950 Hard problems solved — elite tier." },
      { name: "Completionist", plus: true, reason: "3981 total problems solved — elite tier." },
      { name: "Streak Keeper", plus: true, reason: "365 day streak — elite tier." },
      { name: "Polymath", plus: true, reason: "46 topics solved — elite tier." },
      { name: "Specialist", plus: true, reason: "18 hard-tier topics solved — elite tier." },
      { name: "Polyglot", plus: true, reason: "7 languages used — elite tier." },
      { name: "Sharpshooter", plus: true, reason: "100 % acceptance rate — elite tier." },
    ],
    contestRating: 2288.577537935694,
    contestsAttended: 19,
    totalSolved: 3981,
    easySolved: 952,
    mediumSolved: 2079,
    hardSolved: 950,
    topicsSolved: 46,
    easyTopicsSolved: 10,
    mediumTopicsSolved: 18,
    hardTopicsSolved: 18,
    languagesUsed: 7,
    reputation: 173,
    activeDays: 365,
  },
  {
    username: "lee215",
    name: "lee",
    avatarUrl: "https://assets.leetcode.com/users/lee215/avatar_1551541889.png",
    country: "cn",
    stats: { pac: 65, sho: 77, pas: 93, dri: 83, def: 76, phy: 68 },
    position: "CM",
    family: "Playmaker",
    baseOvr: 81,
    overall: 82,
    finish: "red",
    archetype: "Sprinter",
    archetypeBlurb: "the engine — a daily-driver who never slows down",
    legacy: 0.09178774970897462,
    skillMoves: 5,
    weakFoot: 4,
    workRateAttack: "High",
    workRateDefense: "High",
    style: "Industrious",
    playstyles: [
      { name: "Polymath", plus: true, reason: "46 topics solved — elite tier." },
      { name: "Specialist", plus: true, reason: "18 hard-tier topics solved — elite tier." },
      { name: "Polyglot", plus: true, reason: "7 languages used — elite tier." },
      { name: "Sharpshooter", plus: true, reason: "91 % acceptance rate — elite tier." },
      { name: "Ranked", plus: true, reason: "2204 contest rating — elite tier." },
      { name: "Hard Hitter", plus: false, reason: "140 Hard problems solved." },
      { name: "Contest Grinder", plus: false, reason: "27 contests attended." },
      { name: "Completionist", plus: false, reason: "646 total problems solved." },
    ],
    contestRating: 2204.316,
    contestsAttended: 27,
    totalSolved: 646,
    easySolved: 122,
    mediumSolved: 384,
    hardSolved: 140,
    topicsSolved: 46,
    easyTopicsSolved: 10,
    mediumTopicsSolved: 18,
    hardTopicsSolved: 18,
    languagesUsed: 7,
    reputation: 229707,
    activeDays: 45,
  },
];

// Usernames from the baked showcase — enumerated for the sitemap (per-user
// pages are generated on demand, so only these get pre-listed).
export const SAMPLE_USERNAMES: string[] = SAMPLE_CARDS.map((c) => c.username);
